### ISSUE TITLE
Will more updates come?

### ISSUE THREAD

**Issue by iampawan** [redDwarf03/ledger_dart_lib#8]
Hey @redDwarf03, are you still working on this and NanoX implementation?

**Comment by redDwarf03** [comment]
hello. i will work again for the end of the year
but for the moment NanoS
Don't hesitate to contribute :)

**Comment by iampawan** [comment]
@redDwarf03 I have worked on Nano X before and I wrote a library for it but I am facing some issues. Do you think you can help me in fixing those?

**Comment by redDwarf03** [comment]
yes i will try. it could be interesting to do a single library and not separate Nano S and Nano X.
Are you agree with that ?
i'm in contact with ledger team. i would like to integrate the flutter library in the official ledger repo.

**Comment by iampawan** [comment]
Yes, That should be fine too. Let's connect may be ?

**Comment by redDwarf03** [comment]
yes. thanks. i sent you a message by twitter

**Comment by fossephate** [comment]
I know this issue is closed but this seems to be exactly what I'm looking for, or will at least save me some time, correct me if I'm wrong but this library seems to only be for flutter web projects? I'm assuming it uses WebUSB and that's why, but my app is unfortunately not web based :/

@iampawan The Nano X implementation is intriguing, I've worked with HID and bluetooth protocols in the past and might be able to offer some help

**Comment by redDwarf03** [comment]
The aim of this lib is to be multiplatforms. For the moment it works correctly in web but https://pub.dev/packages/hid is a good way for desktop.
I will work on it i hope for the next of the year. Don't hesitate to contribute
See: readme on the github repo
